<?php
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
if ($_items): ?>
<div class="compares" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">
    <div class="icon">
		<?php if($_helper->getItemCount() > 0): ?>
		<span class="amount"><?php echo $_helper->getItemCount() ?></span>
		<?php endif ?>
    </div>
</div>
<?php endif ?>