<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <?php if( $this->isExpanded() ): ?>
        <div class="sort-by">
             <fieldset class="sort-by">
                <label><?php echo $this->__('Razvrsti') ?></label>
                <select onchange="setLocation(this.value)">
                    <option aria-label="<?php echo $this->__('featured') ?>" value="<?php echo $this->getOrderUrl('position', 'asc') ?>"<?php if($this->isOrderCurrent('position') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('featured') ?>
                    </option>
                    <option aria-label="<?php echo $this->__('lowest price') ?>" value="<?php echo $this->getOrderUrl('price', 'asc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('lowest price') ?>
                    </option>
                    <option aria-label="<?php echo $this->__('highest price') ?>" value="<?php echo $this->getOrderUrl('price', 'desc') ?>"<?php if($this->isOrderCurrent('price') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('highest price') ?>
                    </option>
                    <option aria-label="<?php echo $this->__('name A-Z') ?>" value="<?php echo $this->getOrderUrl('name', 'asc') ?>"<?php if($this->isOrderCurrent('name') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('name A-Z') ?>
                    </option>
                    <option aria-label="<?php echo $this->__('name Z-A') ?>" value="<?php echo $this->getOrderUrl('name', 'desc') ?>"<?php if($this->isOrderCurrent('name') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('name Z-A') ?>
                    </option>
                    <option aria-label="<?php echo $this->__('newest to oldest') ?>" value="<?php echo $this->getOrderUrl('created_at', 'desc') ?>"<?php if($this->isOrderCurrent('created_at') && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('newest to oldest') ?>
                    </option>
                    <option aria-label="<?php echo $this->__('oldest to newest') ?>" value="<?php echo $this->getOrderUrl('created_at', 'asc') ?>"<?php if($this->isOrderCurrent('created_at') && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                        <?php echo $this->__('oldest to newest') ?>
                    </option>
                </select>
            </fieldset> 
        </div>
    <?php endif; ?>
    <?php echo $this->getPagerHtml() ?>
    <div class="clear"></div>
</div>
<?php endif ?>