<?php $lazy = Mage::getDesign()->getSkinUrl('images/blank.gif');
if(count($this->getItemCollection()->getItems())): ?>
<div class="priporocamo">
	<div class="title">
    	<h2><?php echo $this->__('You may also be interested in the following product(s)') ?>:</h2>
	</div>
    <?php $this->resetItemsIterator() ?>
	<div class="products-grid top ups owl-carousel owl-theme">
    <?php $i=1; $_columnCount = 20; for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_product=$this->getIterableItem()): ?>
				<div id="<?php echo $id = $_product->getId(); ?>" class="item">
				<div class="okvir">
					<div  class="product-image">
						<!-- zacetek triger -->
						<?php  $now = date("Y-m-d H:m:s"); $newFromDate = $_product->getNewsFromDate(); $newToDate = $_product->getNewsToDate(); ?>                                               
						<?php if($newFromDate < $now && $newToDate > $now): ?>
							<div class="novo"><?php echo $this->__('novo') ?></div>
						<?php endif; ?> 
						<?php $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());
							 $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
							 if ($_regularPrice != $_finalPrice):
							 $getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);
							 $finalpercentage = 100 - $getpercentage; ?> 
							<div class="ceneje <?php if($newFromDate < $now && $newToDate > $now): ?>premik<?php endif; ?> ">-<?php echo number_format($finalpercentage, 0); ?>%</div>
						<?php endif; ?> 
						<!-- konec triger -->

						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>">
							<img class="owl-lazy" src="<?php echo $lazy; ?>" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(362,272); ?>" width="362" height="272" id="product-collection-image-<?php echo $_product->getId(); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
						</a>
					</div>
					<div class="content">
						<?php
						// Provides extra blocks on which to hang some features for products in the list
						// Features providing UI elements targeting this block will display directly below the product name
						if ($this->getChild('name.after')) {
							$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
							foreach ($_nameAfterChildren as $_nameAfterChildName) {
								$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
								$_nameAfterChild->setProduct($_product);
								echo $_nameAfterChild->toHtml();
							}
						}
						?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-name">
							<h2>
								<strong><?php echo $this->htmlEscape($_product->getName()) ?></strong>
							</h2> 
						</a>
						<?php echo $this->getPriceHtml($_product, true) ?>
					</div>
					<div class="action">

						<?php if($_product->isSaleable()): ?>
							<?php if(($_product->getData('has_options')) or ($_product->isConfigurable())): ?>
								<button type="button" title="<?php echo $this->__('Select options') ?>" class="button btn-cart options" onclick="setLocation('<?php echo $_product->getUrl() ?>')"><span><span><?php echo $this->__('Select options') ?></span></span></button>
							<?php else: ?>
								<?php $_cartUrl = $this->getAddToCartUrlCustom($_product, [], false); ?>
								<button type="button"
										title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
										class="button btn-cart"
										onclick="customFormSubmit('<?php echo $_cartUrl ?>', '<?php echo $_params ?>', 'post')">
									<span><span><?php echo $this->__('Add to Cart') ?></span></span>
								</button>
							<?php endif; ?>
						<?php else: ?>
							<button type="button" title="<?php echo $this->__('Out of stock') ?>" class="button btn-cart disabled" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
						<?php endif; ?>
					</div>
				</div>
				</div>
            <?php endif; ?>
        <?php $i++; endfor; ?>
    <?php endfor; ?>
   	</div>
    <div class="clear"></div>
</div>
<?php endif; ?>