<?php $bannerCollection = $this->_getCollection(); ?>
<?php if(($bannerCollection->count())>0) : ?>
<?php $imageCollection = $this->_getBannerImageCollection($bannerCollection); ?>
<?php foreach ($imageCollection as $item) : ?>
	<?php 
		$height = $item['height']; 
		$width = $item['width']; 

		$content = $item['content']; 
		$images = $this->getSortedImages($content);
	?>
	<?php if(isset($images) && !empty($images) && count($images)>0) : ?>
<div class="banner_bottom">
	<ul>
	<?php $i =1; foreach($images as $image): $i++;
	$label = $image['label'];
	$content = $image['html'];
	?>
		<li>
			<a <?php if(!empty($image['link'])): ?> href="<?php echo $image['link'];?>"<?php else:?> href="#" <?php endif;?> title="<?php echo $label; ?>">
				<div class="img">
					<picture>
						<img class="lazy" loading="lazy" height="<?php echo $height ?>" width="<?php echo $width ?>" data-src="<?php echo $this->helper('banner')->resizeImg($image['file'],$width,$height,true);?>"  alt="<?php if($label) { echo $label; } else { echo strip_tags($content); } ?>" />
					</picture>	
				</div>
				<?php if($content): ?>
				<div class="content">
					<?php if($label): ?><h2><?php echo $label; ?></h2><?php endif?>
					<p><?php echo strip_tags($content,'<strong>,<b>,<a>,<u>'); ?></p>
				</div>
				<?php endif; ?>
			</a>
		</li>
	<?php endforeach;?>
	</ul>
	<div class="clear"></div>
</div>
	<?php endif;?>
<?php endforeach;?>
<?php endif; ?>