<?php
/**
 * @category   MagentoPycho
 * @package    MagentoPycho_Lightboxes
 * @author     magepsycho@gmail.com
 * @website    http://www.magepsycho.com
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$helper = Mage::helper('lightboxes');
if($helper->getConfig('active')):
	echo "<!-- jQuery LightBoxes -->". PHP_EOL;
    $moduleName         = $this->getRequest()->getModuleName();
    $controllerName     = $this->getRequest()->getControllerName();
    $actionName         = $this->getRequest()->getActionName();
    #echo $moduleName . '|' . $controllerName . '|' . $actionName;
    if($helper->getConfig('include_globally', 'lightboxes_confliction') || (in_array($moduleName, array('catalog', 'review')) && $controllerName == 'product' && in_array($actionName, array('view', 'list')))):
?>
	<?php if($helper->getConfig('include_jquery', 'lightboxes_confliction') && $helper->getConfig('include_jquery_in', 'lightboxes_confliction') == 'head'): 	?>
		<?php echo $this->getChildHtml('jquery_inclusion'); ?>
	<?php endif; ?>

    <?php if($helper->getConfig('include_lighboxes_in', 'lightboxes_confliction') == 'head'): ?>
	<?php echo $this->getChildHtml('lightboxes_inclusion'); ?>
	<?php endif; ?>

	<?php if($helper->getConfig('include_initialization_in', 'lightboxes_confliction') == 'head'): ?>
	<?php echo $this->getChildHtml('lightboxes_initialization'); ?>
	<?php endif; ?>

	<?php if($helper->getConfig('include_globally', 'lightboxes_confliction') && $helper->getConfig('global_initialization_code', 'lightboxes_confliction', 0)): ?>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			<?php echo $helper->getConfig('global_initialization_code', 'lightboxes_confliction'); ?>
		});
	</script>
	<?php endif; ?>

    <?php endif; ?>
<?php
echo "<!-- //jQuery LightBoxes -->" . PHP_EOL;
endif; //end active ?>