<?php
$helper = Mage::helper('lightboxes');
?>
<?php if($helper->getConfig('include_jquery_from', 'lightboxes_confliction') == 'local') :?>
<script type="text/javascript" src="<?php echo $helper->getLightboxUrl(); ?>/jQuery/1.7.1/jquery.min.js"></script>
<?php else: ?>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $helper->getLightboxUrl(); ?>/no-conflict.js"></script>