<?php
if(Mage::getStoreConfig('zero1_gdpr/options/enabled'))
{
	?>
<div id="cookiealert" class="cookiealert" style="display: none;">
    <div class="message">
        <p>
            <?php echo $this->__('This website uses cookies to ensure proper functionality of the shopping cart and checkout progress. By continuing to browse the site you are agreeing to the use of cookies.');?>
            <a href="<?php echo Mage::getBaseUrl(); ?>privacy-policy-cookie-restriction-mode"><?php echo $this->__('Click here to learn about cookie settings.'); ?></a>
        </p>
    </div> 
    <div class="buttons-set">
        <button type="button" class="button" onclick="javascript:acceptCookieAlert();" title="<?php echo $this->__('Accept');?>"><span><span><?php echo $this->__('Accept');?></span></span></button>
        <button type="button" class="button decline" onclick="javascript:declineCookieAlert();" title="<?php echo $this->__('Decline');?>"><span><span><?php echo $this->__('Decline');?></span></span></button>
    </div>
</div>

<script type="text/javascript">
function closeCookieAlert() {
    Mage.Cookies.set('cookieAlertClosedFlag', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
    document.getElementById('cookiealert').style.display = 'none';
}

function acceptCookieAlert() {
    closeCookieAlert();
    Mage.Cookies.set('cookieAlertState', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
    loadCookieScript();
}

function declineCookieAlert() {
    closeCookieAlert();
    Mage.Cookies.set('cookieAlertState', 0, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364)));
}

function loadCookieScript() {
<?php
$gtmContainerId = Mage::getStoreConfig('zero1_gdpr/configuration/gtm_container_id');
if (!empty($gtmContainerId)) {
    ?>
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.text = 'var Translator = new Translate([]);';
    document.body.appendChild(script);
    
    var gtm_tag = document.createElement('script');
    gtm_tag.type = 'text/javascript';
    gtm_tag.text = '(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);})(window,document,\'script\',\'dataLayer\',\'<?php echo $gtmContainerId; ?>\');';
    document.body.appendChild(gtm_tag);
    <?php
}
?>
}

if (!Mage.Cookies.get('cookieAlertClosedFlag')) {
    document.getElementById('cookiealert').style.display = '';
}

if (Mage.Cookies.get('cookieAlertState') == 1) {
    loadCookieScript();
}
</script>
	<?php
}
