<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<div class="product-image">
    <!-- zacetek triger -->
    <?php $now = date("Y-m-d H:m:s");
    $newFromDate = $_product->getNewsFromDate();
    $newToDate = $_product->getNewsToDate(); ?>
    <?php if ($newFromDate < $now && $newToDate > $now) : ?>
        <div class="novo"><?php echo $this->__('novo') ?></div>
    <?php endif; ?>
    <?php $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());
    $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
    if ($_regularPrice != $_finalPrice) :
        $getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);
        $finalpercentage = 100 - $getpercentage; ?>
        <div class="ceneje <?php if ($newFromDate < $now && $newToDate > $now) : ?>premik<?php endif; ?> ">-<?php echo number_format($finalpercentage, 0); ?>%</div>
    <?php endif; ?>
    <!-- konec triger -->
    <div class="product-image-gallery" >
        <link rel="preload" media="(min-width: 640px)" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(865) ?>" />
        <link rel="preload" media="(max-width: 640px)" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(640) ?>" />
        <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" rel="lightbox[gallery1]" title="<?php echo $this->escapeHtml($this->getImageLabel()) ?>">
            <picture>
                <source media="(max-width: 640px)" srcset="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(640) ?>" width="640" height="640">
                <img id="image-main" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(865) ?>" width="865" height="865" class="gallery-image visible" alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>" title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
            </picture>
        </a>
    </div>
</div>


<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <div class="product-image-thumbs owl-carousel owl-theme" style="display: block !important;">
    <?php $i=1; $image = $_product->getImage(); foreach ($this->getGalleryImages() as $_image): ?>
        <?php if ($this->isGalleryImageVisible($_image)): ?>
		<?php if($image != $_image->getFile()): ?>
            <a class="thumb-link" rel="lightbox[gallery1]" href="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile()); ?>" title="<?php if($_image->getLabel()) { echo $this->escapeHtml($_image->getLabel()); } else { echo $_product->getName(); } ?>" data-image-index="<?php echo $i; ?>">
                <?php if($i == 1): ?>
                    <link rel="preload" media="(min-width: 640px)" href="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(210); ?>" />
                    <link rel="preload" media="(max-width: 640px)" href="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(495); ?>" />
                <?php endif; ?>
                <picture>
                    <source media="(max-width: 640px)" srcset="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(210); ?>" width="210" height="210">
                    <img <?php if($i !== 3): ?>class="lazy" data-<?php endif; ?>src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(420); ?>" width="420" height="420" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                </picture>
            </a>
        <?php endif; ?>
        <?php endif; ?>
    <?php $i++; endforeach; ?>
    </div>
</div>
<?php endif; ?>

<?php echo $this->getChildHtml('after'); ?>