<?php if ($this->getIsActive()):

    $rnd_str = "";
    $base_str = "0123456789abcdefghijklmnopqrstuvwxyz";
    $su = strlen($base_str) - 1;
    $rnd_str = substr($base_str, rand(0,$su), 1).substr($base_str, rand(0,$su), 1).substr($base_str, rand(0,$su), 1);

?>
	<div class="degriz_gdprnewsletter gdprnewsletter_<?php echo $rnd_str; ?>">
		<label><input class="gdprnewsletter_confirmation checkbox required-entry" name="gdprnewsletter_confirmation" type="checkbox" id="gdprnewsletter_confirmation"><?php echo $this->getText() ?></label> <span href="javascript:void(0)" class="gdprnewsletter_box_open"><label class="gdprlabel_text" for="gdprpopup_<?php echo $rnd_str; ?>"><?php echo $this->getLink() ?></label></span>
		<input class="gdprpopup-state" id="gdprpopup_<?php echo $rnd_str; ?>" type="checkbox" />
		<div class="gdprpopup_class">
			<label class="gdprpopup_bg" for="gdprpopup_<?php echo $rnd_str; ?>"></label>
			<div class="gdprpopup_inner">
				<div>
					<label class="gdprpopup_close" for="gdprpopup_<?php echo $rnd_str; ?>"></label>
			        <div class="gdprpopup_box_inner std">
						<?php echo $this->getMessage() ?>
			        </div>
			        <div class="gdprpopup_box_subscribe">
			            <div class="gdprpopup_box_subscribe_form">
							<span class="button" href="javascript:void(0)"><label class="gdprlabel_button gdprpopup_yes" for="gdprpopup_<?php echo $rnd_str; ?>"><?php echo $this->__('Yes, I agree'); ?></label></span>
							<span class="button" href="javascript:void(0)"><label class="gdprlabel_button gdprpopup_no" for="gdprpopup_<?php echo $rnd_str; ?>"><?php echo $this->__("No, i don't agree"); ?></label></span>
			            </div>
			        </div>
		        </div>
			</div>
		</div>
	</div>
<script type='text/javascript'>
	jQuery(function($) {
	    var $gdprBlock = $('.gdprnewsletter_<?php echo $rnd_str; ?>');
	    var $gdprInput = $gdprBlock.find('input[name="gdprnewsletter_confirmation"]');
	    var $blockButton = $gdprBlock.closest('form').find('button[type="submit"]');
	    $blockButton.prop('disabled', true);
	    $gdprBlock.find('.gdprpopup_yes').click(function(){
	        $gdprInput.prop('checked', true);
	        $gdprInput.trigger('change');
	    });
	    $gdprBlock.find('.gdprpopup_no').click(function(){
	        $gdprInput.prop('checked', false);
	        $gdprInput.trigger('change');
	    });
	    $gdprInput.change(function() {
	        if(this.checked)
	            $blockButton.prop('disabled', false);
	        else
	            $blockButton.prop('disabled', true);    
	    });
	    $gdprBlock.find('#gdprpopup_<?php echo $rnd_str; ?>').change(function() {
	        $('body,html').toggleClass('modal_opened');
	        $gdprBlock.find('.gdprpopup_class').toggleClass('popup_opened');
	    });
	});
	jQuery.noConflict();
</script>
<?php endif; ?>