<div class="slike-container">
<div class="slike">
    <div class="wk-gallery wk-gallery-wall clearfix round polaroid margin ">           
	<a href="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika1.jpg" title="Malinca ekipa | Andreja in Nastja"><div><img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika1_m.jpg" alt="ekipa1" height="145" width="220"><p class="title">Malinca ekipa | Andreja in Nastja</p></div></a>   
	<a href="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika2.jpg" title="Malinca ekipa | Andreja"><div><img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika2_m.jpg" alt="ekipa2" height="145" width="220"><p class="title">Malinca ekipa | Nastja in Andreja</p></div></a>
	<a href="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika3.jpg" title="Malinca ekipa | Nastja in Andreja"><div><img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika3_m.jpg" alt="ekipa4" height="145" width="220"><p class="title">Malinca ekipa | Nastja in Andreja</p></div></a>
	<a href="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika4.jpg"title="Malinca ekipa | Andreja"><div><img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika4_m.jpg" alt="ekipa5" height="145" width="220"><p class="title">Malinca ekipa | Nastja in Andreja</p></div></a>
    <a href="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika5.jpg" title="Malinca ekipa | Nastja"><div><img src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/galerija/slika5_m.jpg" alt="ekipa6" height="145" width="220"><p class="title">Malinca ekipa | Nastja in Andreja</p></div></a>       
    <div class="clear"></div>
    </div>
</div>
</div>
<div class="clear"></div>